# Generated by Django 5.0.1 on 2024-03-21 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="offer",
            name="offer_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reservation.offertype"
            ),
        ),
    ]
