# Generated by Django 5.0.1 on 2024-03-21 00:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0002_offertype_alter_offer_offer_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offertype",
            name="description",
        ),
    ]
